# Generated by Django 5.0.2 on 2024-03-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_extendeduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
