# Generated by Django 5.0.2 on 2024-03-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_applicant_created_at_alter_company_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="applicants",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="job_application",
                to="core.applicant",
            ),
        ),
    ]
