# Generated by Django 5.0.2 on 2024-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_jobpost_applicants"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(default="São Paulo, Brazil", max_length=255),
        ),
    ]
