# Generated by Django 5.0.2 on 2024-03-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_company_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="location",
            field=models.CharField(default="São Paulo, Brazil", max_length=255),
        ),
    ]
